language: perl

perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - sudo apt-get update
  - sudo apt-get install texlive-full

before_script:
  - ./setup/build-perl-modules.sh
  - ./setup/build-devel.sh
  
script:
  - perl Makefile.PL
  - env PERL5LIB=`pwd`/thirdparty/lib/perl5  thirdparty/bin/cover -test -report coveralls

