language: perl

perl:
  - "5.18"


before_install:
  - curl -L https://raw.githubusercontent.com/krlmlr/texlive-squashfs/master/out/texlive.tar.xz | tar xJC ~
  - cpanm --notest Devel::Cover::Report::Coveralls IO::Socket::SSL Mojolicious

script:
  - env PATH="$HOME/texlive/bin/x86_64-linux:$PATH" cover -test -report coveralls

