language: perl

perl:
  - "5.18"

before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-luatex texlive-latex-base texlive-xetex
  - cpanm --notest Devel::Cover::Report::Coveralls IO::Socket::SSL Mojolicious

script:
  - env PATH="/opt/texbin:$PATH" cover -test -report coveralls

