sudo: false

addons:
  apt:
    packages:
    - poppler-utils

language: perl

perl:
  - "5.18"
  - "5.20"
  - "5.22"

before_install:
  - curl -L https://github.com/raphink/travis-texlive/releases/download/2015-07-14_05/texlive.tar.xz  | tar xJC ~
  - cpanm --notest Devel::Cover::Report::Coveralls IO::Socket::SSL Mojolicious

script:
  - env PATH="$HOME/texlive/bin/x86_64-linux:$PATH" cover -test -report coveralls
